"""Build one global speed-layer snapshot from immutable S3 batch deltas.

AWS Lambda can process Kinesis records in several execution environments.
Each environment has isolated memory, so a snapshot written directly by one
Lambda invocation is only a local diagnostic view. The durable source of truth
is the collection of immutable documents under ``speed/batches/``.

This module reads those documents, removes retry duplicates, rebuilds the
recent event-time sliding window and writes a single global snapshot suitable
for the serving layer.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import dataclass
from typing import Any, Iterable

import boto3

from speed.batch_delta_store import DEFAULT_BATCH_PREFIX
from speed.lambda_handler import detect_anomalies
from speed.snapshot_store import persist_speed_snapshot
from speed.window_analytics import SlidingWindowAnalytics


DEFAULT_GLOBAL_SNAPSHOT_KEY = "speed/global_snapshot.json"
DEFAULT_RESULTS_BUCKET = "scp-speed-results-25186396"


@dataclass(frozen=True)
class AggregationStatistics:
    """Counters describing one global aggregation run."""

    scanned_objects: int
    valid_documents: int
    invalid_documents: int
    raw_events: int
    unique_events: int
    duplicate_events: int
    invalid_events: int

    def as_dict(self) -> dict[str, int]:
        """Return JSON-serialisable statistics."""

        return {
            "scanned_objects": self.scanned_objects,
            "valid_documents": self.valid_documents,
            "invalid_documents": self.invalid_documents,
            "raw_events": self.raw_events,
            "unique_events": self.unique_events,
            "duplicate_events": self.duplicate_events,
            "invalid_events": self.invalid_events,
        }


def _event_identity(event: dict[str, Any]) -> str:
    """Return a stable identity used to remove retry duplicates.

    ``event_id`` is preferred because it is generated by the producer.
    The Kinesis sequence number is the second choice. A deterministic hash is
    retained as a final defensive fallback for older delta documents.
    """

    event_id = str(event.get("event_id") or "").strip()
    if event_id:
        return f"event_id:{event_id}"

    sequence_number = str(event.get("sequence_number") or "").strip()
    if sequence_number:
        return f"sequence_number:{sequence_number}"

    canonical_fields = {
        "timestamp": event.get("timestamp"),
        "client_ip": event.get("client_ip"),
        "method": event.get("method"),
        "endpoint": event.get("endpoint"),
        "status_code": event.get("status_code"),
        "response_bytes": event.get("response_bytes"),
        "source": event.get("source"),
    }

    canonical_json = json.dumps(
        canonical_fields,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")

    return "fallback:" + hashlib.sha256(canonical_json).hexdigest()


def _extract_events(document: Any) -> list[Any] | None:
    """Validate one batch-delta document and return its event list."""

    if not isinstance(document, dict):
        return None

    if document.get("document_type") != "speed_batch_delta":
        return None

    events = document.get("events")
    if not isinstance(events, list):
        return None

    return events


def aggregate_delta_documents(
    documents: Iterable[Any],
    *,
    window_seconds: int = 300,
    error_rate_threshold: float = 0.50,
    minimum_requests: int = 2,
) -> dict[str, Any]:
    """Aggregate in-memory batch-delta documents into one global view."""

    analytics = SlidingWindowAnalytics(window_seconds=window_seconds)

    seen_identities: set[str] = set()
    unique_event_count = 0

    scanned_objects = 0
    valid_documents = 0
    invalid_documents = 0
    raw_events = 0
    duplicate_events = 0
    invalid_events = 0

    for document in documents:
        scanned_objects += 1
        events = _extract_events(document)

        if events is None:
            invalid_documents += 1
            continue

        valid_documents += 1
        raw_events += len(events)

        for event in events:
            if not isinstance(event, dict):
                invalid_events += 1
                continue

            identity = _event_identity(event)

            if identity in seen_identities:
                duplicate_events += 1
                continue

            try:
                analytics.add_event(event)
            except (KeyError, TypeError, ValueError):
                invalid_events += 1
                continue

            seen_identities.add(identity)
            unique_event_count += 1

    snapshot = analytics.snapshot()

    anomalies = detect_anomalies(
        snapshot=snapshot,
        error_rate_threshold=error_rate_threshold,
        minimum_requests=minimum_requests,
    )

    statistics = AggregationStatistics(
        scanned_objects=scanned_objects,
        valid_documents=valid_documents,
        invalid_documents=invalid_documents,
        raw_events=raw_events,
        unique_events=unique_event_count,
        duplicate_events=duplicate_events,
        invalid_events=invalid_events,
    )

    summary = {
        **statistics.as_dict(),
        "window_event_count": snapshot["window_event_count"],
        "anomaly_count": len(anomalies),
    }

    return {
        "summary": summary,
        "anomalies": anomalies,
        "snapshot": snapshot,
    }


def list_batch_delta_keys(
    *,
    s3_client: Any,
    bucket: str,
    prefix: str = DEFAULT_BATCH_PREFIX,
) -> list[str]:
    """List all JSON delta keys under a prefix, including pagination."""

    effective_prefix = prefix.strip("/") + "/"
    continuation_token: str | None = None
    keys: list[str] = []

    while True:
        request: dict[str, Any] = {
            "Bucket": bucket,
            "Prefix": effective_prefix,
        }

        if continuation_token:
            request["ContinuationToken"] = continuation_token

        response = s3_client.list_objects_v2(**request)

        contents = response.get("Contents", [])
        if isinstance(contents, list):
            for item in contents:
                if not isinstance(item, dict):
                    continue

                key = item.get("Key")
                if isinstance(key, str) and key.endswith(".json"):
                    keys.append(key)

        if not response.get("IsTruncated"):
            break

        continuation_token = response.get("NextContinuationToken")
        if not continuation_token:
            break

    return sorted(set(keys))


def load_batch_delta_documents(
    *,
    s3_client: Any,
    bucket: str,
    keys: Iterable[str],
) -> list[Any]:
    """Load JSON documents from S3 while retaining malformed entries."""

    documents: list[Any] = []

    for key in keys:
        try:
            response = s3_client.get_object(Bucket=bucket, Key=key)
            raw_body = response["Body"].read()
            document = json.loads(raw_body.decode("utf-8-sig"))
        except (KeyError, TypeError, ValueError, UnicodeDecodeError, json.JSONDecodeError):
            documents.append(None)
            continue

        documents.append(document)

    return documents


def aggregate_s3_batch_deltas(
    *,
    bucket: str,
    prefix: str = DEFAULT_BATCH_PREFIX,
    output_key: str = DEFAULT_GLOBAL_SNAPSHOT_KEY,
    window_seconds: int = 300,
    error_rate_threshold: float = 0.50,
    minimum_requests: int = 2,
    s3_client: Any | None = None,
) -> dict[str, Any]:
    """Read all durable deltas and persist one global S3 snapshot."""

    client = s3_client if s3_client is not None else boto3.client("s3")

    keys = list_batch_delta_keys(
        s3_client=client,
        bucket=bucket,
        prefix=prefix,
    )

    documents = load_batch_delta_documents(
        s3_client=client,
        bucket=bucket,
        keys=keys,
    )

    aggregated = aggregate_delta_documents(
        documents,
        window_seconds=window_seconds,
        error_rate_threshold=error_rate_threshold,
        minimum_requests=minimum_requests,
    )

    persistence = persist_speed_snapshot(
        summary=aggregated["summary"],
        anomalies=aggregated["anomalies"],
        snapshot=aggregated["snapshot"],
        s3_client=client,
        bucket=bucket,
        key=output_key,
    )

    return {
        **aggregated,
        "source": {
            "bucket": bucket,
            "prefix": prefix.strip("/"),
            "object_count": len(keys),
        },
        "persistence": persistence,
    }


def main() -> None:
    """Run the global aggregation from the command line."""

    parser = argparse.ArgumentParser(
        description=(
            "Aggregate immutable Lambda batch deltas into one global "
            "speed-layer snapshot."
        )
    )

    parser.add_argument("--bucket", default=DEFAULT_RESULTS_BUCKET)
    parser.add_argument("--prefix", default=DEFAULT_BATCH_PREFIX)
    parser.add_argument("--output-key", default=DEFAULT_GLOBAL_SNAPSHOT_KEY)
    parser.add_argument("--window-seconds", type=int, default=300)
    parser.add_argument("--error-rate-threshold", type=float, default=0.50)
    parser.add_argument("--minimum-requests", type=int, default=2)

    arguments = parser.parse_args()

    result = aggregate_s3_batch_deltas(
        bucket=arguments.bucket,
        prefix=arguments.prefix,
        output_key=arguments.output_key,
        window_seconds=arguments.window_seconds,
        error_rate_threshold=arguments.error_rate_threshold,
        minimum_requests=arguments.minimum_requests,
    )

    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
